const MODULE_NAME = 'API_MODULE';

const MUTATIONS = {
  SET_AXIOS: 'SET_AXIOS',
  SET_ENVIRONMENT: 'SET_ENVIRONMENT',
};
/* getters */
const GETTERS = {};

const MODULE_GETTERS = {};

const ACTIONS = {
  // common
  INIT: 'INIT',
  SEND: 'SEND',
  SEND_AUTHORIZED: 'SEND_AUTHORIZED',
  // admin
  LOAD_STUDY_POLICIES_ADMIN: 'LOAD_STUDY_POLICIES_ADMIN',
  CREATE_STUDY_POLICY_ADMIN: 'CREATE_STUDY_POLICY_ADMIN',
  CHANGE_STUDY_POLICY_STATUS_ADMIN: 'CHANGE_STUDY_POLICY_STATUS_ADMIN',
  DELETE_STUDY_POLICIES_ADMIN: 'DELETE_STUDY_POLICIES_ADMIN',
};

const MODULE_ACTIONS = {
  // common
  [ACTIONS.INIT]: `${MODULE_NAME}/${ACTIONS.INIT}`,
  [ACTIONS.SEND]: `${MODULE_NAME}/${ACTIONS.SEND}`,
  [ACTIONS.SEND_AUTHORIZED]: `${MODULE_NAME}/${ACTIONS.SEND_AUTHORIZED}`,
  // admin
  [ACTIONS.LOAD_STUDY_POLICIES_ADMIN]: `${MODULE_NAME}/${ACTIONS.LOAD_STUDY_POLICIES_ADMIN}`,
  [ACTIONS.CREATE_STUDY_POLICY_ADMIN]: `${MODULE_NAME}/${ACTIONS.CREATE_STUDY_POLICY_ADMIN}`,
  [ACTIONS.CHANGE_STUDY_POLICY_STATUS_ADMIN]: `${MODULE_NAME}/${ACTIONS.CHANGE_STUDY_POLICY_STATUS_ADMIN}`,
  [ACTIONS.DELETE_STUDY_POLICIES_ADMIN]: `${MODULE_NAME}/${ACTIONS.DELETE_STUDY_POLICIES_ADMIN}`,
};

export {MODULE_NAME, MODULE_ACTIONS, ACTIONS, MUTATIONS, MODULE_GETTERS, GETTERS};