const MODULE_NAME = 'ADMIN_MODULE';

/* getters */
const GETTERS = {
  GET_STUDY_POLICIES: 'GET_STUDY_POLICIES',
};

const MODULE_GETTERS = {
  [GETTERS.GET_STUDY_POLICIES]: `${MODULE_NAME}/${GETTERS.GET_STUDY_POLICIES}`,
};

/* mutations */
const MUTATIONS = {
  SET_STUDY_POLICIES: 'SET_STUDY_POLICIES',
};

/* actions */
const ACTIONS = {
  // studyPolicies
  LOAD_STUDY_POLICIES: 'LOAD_STUDY_POLICIES',
  CREATE_STUDY_POLICY: 'CREATE_STUDY_POLICY',
  CHANGE_STUDY_POLICY_STATUS: 'CHANGE_STUDY_POLICY_STATUS',
  DELETE_STUDY_POLICIES: 'DELETE_STUDY_POLICIES',
};

const MODULE_ACTIONS = {
  // studyPolicies
  [ACTIONS.LOAD_STUDY_POLICIES]: `${MODULE_NAME}/${ACTIONS.LOAD_STUDY_POLICIES}`,
  [ACTIONS.CREATE_STUDY_POLICY]: `${MODULE_NAME}/${ACTIONS.CREATE_STUDY_POLICY}`,
  [ACTIONS.CHANGE_STUDY_POLICY_STATUS]: `${MODULE_NAME}/${ACTIONS.CHANGE_STUDY_POLICY_STATUS}`,
  [ACTIONS.DELETE_STUDY_POLICIES]: `${MODULE_NAME}/${ACTIONS.DELETE_STUDY_POLICIES}`,
};

export {MODULE_NAME, MODULE_GETTERS, GETTERS, MODULE_ACTIONS, ACTIONS, MUTATIONS};