export default {
  users: [],
  projects: [],
  contents: [],
  studyPolicies: [],
  usagePolicies: [],
  transactions: [],
  emails: [],
  finances: [],
  returnPolicies: [],
  contracts: [],
  acts: [],
  writeOffs: [],
  withdrawalRequests: [],
  returnRequests: [],
  emailTemplates: [],
};